### PR TITLE
Add boilerplates for using webpack

### PR DESCRIPTION
**Pull request by vbence86**
#### Intent
To add boilerplate code that demonstrates how to implement metalJS components using either Soy or JSX templates and bundle them with webpack.

#### Solution
- Added `boilerplate` folder that contains an example package one which employs Soy template and another uses JSX format to implement a Hello World metalJS component
- Registered a `build` script in the corresponding `package.json` that invokes `webpack` programmatically to bundle the metalJS component into one file.
- Registered a `start` script for the JSX boilerplate that kicks off a `WebpackDevServer` using `HotModuleLoader` so that any updates against the JSX templates and CSS assets are displayed on the fly.
- Added an `npm` script to pack the boilerplate folder into `boilerplates.zip` archive

#### How it works
When invoking the `npm build` script it executes the `scripts/build.js` node application that generates the bundle through webpack. The main configuration attributes are fetched from `package.json`. The indispensable attributes are as follows:

```
"publicName": "Modal",
"main": "src/Modal.js",
```
Where `publicName` stands for the name of the metalJS component that will be exposed to the outside world. (e.g.:`window.Modal = { ... }`) and the `main` attribute tells webpack which js file is the entry point.

#### Note
The boilerplate code employs `babel-loader`, `css-loader`, `style-loader` and `sass-loader` so that all JS and SASS assets will be placed automatically into one bundle. 

#### Complementary features
- Webpack Visualizer 
When triggering the `npm build` webpack generates a visual report of the build into the `stats.html` in the package root folder.

captura de pantalla 2017-08-21 a las 9 10 12

### CODE REVIEW

**Comment by robframpton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by robframpton — CHANGES_REQUESTED** [review]
Hey @vbence86,

I think for the boilerplates we should provide as simple a build system as possible, then maybe have a set of advanced examples for things such as the Visualizer and some of the other features you've added.

The package generated by https://www.npmjs.com/package/generator-metal for example, just has a `webpack.config.js` file, and invokes `webpack` as a cli in the npm scripts. I think this approach is more appropriate for the boilerplates as there is a lower barrier of entry, and less custom code.

@jbalsas, do you have anything to add?

**Comment by jbalsas** [comment]
Hey @vbence86, @Robert-Frampton!

Yeah, I agree the boilerplates should be as simple as possible so they can be used as a starting point. Too much stuff and people have to start removing them so it adapts to their needs.

We already have an example for webpack, though: https://github.com/metal/metal-examples/tree/master/custom-build/webpack What's wrong with that one? Does it need updating?

The visualizer and other additions look great, so I'd suggest:
- Update the existing `webpack` example here with the bare-minimum stuff needed to work
- Update the generator with some additional options such as the visualizer, liferay's style guides and so on...

**Comment by vbence86** [comment]
@jbalsas @Robert-Frampton 

These are all good points, I've got to agree. I solely extended the basic boilerplate due vague specification of the task. I had looked through various react-boilerplate projects to sort of understand the level of sophistication we should apply here. Having said that, I'm happy to sort of tear it down to a level it appears helpful for devs without any confusing noise.

@jbalsas I'd actually stumbled into that project through google-search and eventually used it as a foundation of the boilerplate project I came up with. The main differences are as follow:
- Sass support with CSS loader through JS
- Build script uses webpack programmatically so that ES6 syntax can be employed if we increase the version of the node dependency
- HotModuleLoader for rapid development - `yarn start` kicks off a `webpack-dev-server` and navigates to the demo page with livereload activated so as to have all the CSS changes propagated straight into the browser and automatic reload for any updates against Javascript files.
- Webpack build report by Visualizer 
- The moduls get exposed automatically according to the `package.json` attributes

So it appears a reasonable decision to exclude all these from the sort of metal-js 101 examples, but definitely could leverage of them for advanced projects.

**Comment by jbalsas** [comment]
Hey @vbence86, thanks for the explanation! I'd wait for @Robert-Frampton to give some more context as to what was expected from this :)

**Comment by robframpton** [comment]
Hey @vbence86 

Sorry I wasn't more clear in my email. The intention was to fix the zip files that can be downloaded on metaljs.com (issues reported [here](https://github.com/metal/metaljs.com/issues/60), and to create an easier way to maintain/release those zip files to begin with. Right now you just have to unzip them, make changes, and re-zip them (unless they exist in a repo somewhere I don't know about).

Hope that clears things up. Please let me know in the future if you have any clarifying questions on tasks.

**Comment by vbence86** [comment]
@Robert-Frampton Cool, I had a lookthrough at the issue you mentioned (https://github.com/metal/metaljs.com/issues/60). I'm happy to use the repo @jbalsas pointed out as the base, it also almost identical to what is implemented in the current boilerplate projects. The only issue in those is that webpack exposes the modules into the `default` attribute of the given scope (e.g.: Modal -> Modal.default). 

As for the archives, I also added a script to generate the archive through npm as you explained. You can have a look at it in this PR while I'm updating the rest of it.

**Comment by vbence86** [comment]
@Robert-Frampton I've updated the PR according to our discussion. Please cast your eyes over it if you've got some spare time.

Many thanks,
Bence

**Comment by vbence86** [comment]
If you're happy with this simplified version, the only thing will remain is to discuss the archive script so that it will generate the zip files in a structure that makes the upload process smoother.

Currently it's just bundle the boilerplate folder as a whole splitting solely a `boilerplates.zip` out, I reckon it's not the desired result here.

**Comment by robframpton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robframpton** [comment]
Hey @vbence86 

The boilerplates look good, now that the webpack stuff is figured out we can bring in the other parts of the tutorial that is in the original zip file.

screen shot 2017-08-23 at 8 30 18 am

The webpack/build files would be the same in all of the different sections, the only difference is that it increases in complexity and corresponds to the Tutorial section on metaljs.com.

screen shot 2017-08-23 at 8 32 18 am

For the archive functionality, we just need to create two zip files for the jsx/soy folders, it would be nice if it ignores `node_modules` so that the dependencies don't accidentally get bundled as well (this would be easy to accomplish with gulp and [gulp-zip](https://www.npmjs.com/package/gulp-zip) since you would be able to use glob patterns).

Links to the zip files.
JSX: https://hosting-metal.wedeploy.io/downloads/boilerplate-jsx.zip
Soy: https://hosting-metal.wedeploy.io/downloads/boilerplate.zip

**Comment by vbence86** [comment]
@Robert-Frampton Thanks for the detailed explanation. I'll migrate the webpack setup into all these demos and alter the archive task to make it work in way you just described. Though it seems fairly simple task applying the changes against all the demo projects might take up some time. I'll drop you a comment here when it's ready. 

Many thanks,
Bence

**Comment by robframpton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robframpton** [comment]
Awesome. Thanks @vbence86!

**Comment by vbence86** [comment]
@Robert-Frampton No problem, I'll get on with the JSX boilerplates this morning and will let you know once I get it done.

**Comment by vbence86** [comment]
@Robert-Frampton I'm done with all the steps you lined up earlier, as the last bit I've employed gulp-zip to generate the archives as you suggested, it was super easy. I've tested each of the demos individually in an isolated environment so all looks good. Please review when you've got a bit of time. 

Thanks

**Comment by robframpton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robframpton** [comment]
Nice @vbence86! Merging it now, can you generate those zips and send a PR to replace the zips in https://github.com/metal/metaljs.com/tree/master/src/downloads?

**Comment by vbence86** [comment]
@Robert-Frampton Thanks! I'm out of working hours now but will do it first thing on Monday. Have a great weekend.

**Comment by vbence86** [comment]
@Robert-Frampton Thank you, I've added the PR to `metaljs.com` project. https://github.com/metal/metaljs.com/pull/61

**Pull request merged**
